DROP TABLE IF EXISTS
    todo;

CREATE TABLE IF NOT EXISTS
    todo(
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        title VARCHAR(255) DEFAULT NULL,
        content VARCHAR(255) DEFAULT NULL,
        PRIMARY KEY(id)
    )ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
